// Code generated by Stan version 2.14

#ifndef VIFCOPULA_SERVICE_BICOP_SELECT_HPP
#define VIFCOPULA_SERVICE_BICOP_SELECT_HPP

#include <bicopula_stanc.hpp>
#include <stan/services/optimize/bfgs.hpp>
#include <stan/optimization/bfgs.hpp>

namespace vifcopula{

typedef boost::ecuyer1988 rng_t;
typedef vifcopula::bicopula bicopula;
typedef stan::optimization::BFGSLineSearch<bicopula,stan::optimization::BFGSUpdate_HInv<> > Optimizer_BFGS;

double bicop_select(std::vector<double>& u,
                    std::vector<double>& v,
                    int t_max,
                    std::vector<double>& params_out,
                    rng_t& base_rng){

    std::vector<double> params_r(1);
    params_r[0] = 1;
    std::vector<int> params_i(0);
    bool save_iterations = false;
    int refresh = 0;
    int return_code;
    int return_cop = 0;

    bicopula biuv(1,u,v,t_max,base_rng);

    if (biuv.check_Ind()){
        //biuv.set_copula_type(0);
        return return_cop;

    } else {
        const int cop_seq_size = 5;                     // Change the number
        int cop_seq[cop_seq_size] = {1, 3, 4, 5, 6};    // Choose among copula type
        double log_cop[cop_seq_size] = {0, 0, 0, 0, 0};
        double AIC[cop_seq_size] = {0, 0, 0, 0, 0};
        double BIC[cop_seq_size] = {0, 0, 0, 0, 0};
        double lpmax = std::numeric_limits<double>::min();
        double BICmin = std::numeric_limits<double>::max();
        int imax=0;
        for (int i = 0; i < cop_seq_size; i++) {
            biuv.set_copula_type(cop_seq[i]);
            std::stringstream out;
            Optimizer_BFGS bfgs(biuv, params_r, params_i, &out);
            double lp = 0;
            int ret = 0;
            while (ret == 0) {
                ret = bfgs.step();
            }
            lp = bfgs.logp();
            log_cop[i] = lp;
            AIC[i] = -2 * lp + 2 * 1;
            BIC[i] = -2 * lp + log(t_max) * 1;
            // if (lp > lpmax){
            //     lpmax = lp;
            //     imax = i;
            //     // std::vector<double> get_param;
            //     bfgs.params_r(params_out);
            //     //cont_params[t_max+i] = get_param[0];
            // }
            if (BIC[i] < BICmin){
                BICmin = BIC[i];
                imax = i;
                // std::vector<double> get_param;
                bfgs.params_r(params_out);
                //cont_params[t_max+i] = get_param[0];
            }
        }
        return_cop = cop_seq[imax];

    }

    return return_cop;
}   // end func

} // namespace
#endif // VIFCOPULA_SERVICE_BICOP_SELECT_HPP
