// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_vifcopula_RCPPEXPORTS_H_GEN_
#define RCPP_vifcopula_RCPPEXPORTS_H_GEN_

#include <RcppEigen.h>
#include <Rcpp.h>

namespace vifcopula {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("vifcopula", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("vifcopula", "vifcopula_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in vifcopula");
            }
        }
    }

    inline List vifcop(SEXP data_, SEXP init_, SEXP other_) {
        typedef SEXP(*Ptr_vifcop)(SEXP,SEXP,SEXP);
        static Ptr_vifcop p_vifcop = NULL;
        if (p_vifcop == NULL) {
            validateSignature("List(*vifcop)(SEXP,SEXP,SEXP)");
            p_vifcop = (Ptr_vifcop)R_GetCCallable("vifcopula", "vifcopula_vifcop");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_vifcop(Rcpp::wrap(data_), Rcpp::wrap(init_), Rcpp::wrap(other_));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<List >(rcpp_result_gen);
    }

}

#endif // RCPP_vifcopula_RCPPEXPORTS_H_GEN_
