# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Variational inference for factor copula models
#'
#' \code{viofcop} returns variational estimations.
#'
#'
#' @param
#' @param
#' @return
#' @examples
#' viofcop(data, init, other)
#'
#' \dontrun{
#' viofcop(data, init, other)
#' }
#' @export
viofcop <- function(data_, init_, other_) {
    .Call('vifcopula_viofcop', PACKAGE = 'vifcopula', data_, init_, other_)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('vifcopula_RcppExport_registerCCallable', PACKAGE = 'vifcopula')
})
